# -*- coding: utf-8 -*-
"""DNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TweiCYMuzf4uDGnIBAYDzTUvmgziupZW
"""

#Load Dataset

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import struct
import pandas as pd

# === Step 1: Load MNIST Dataset ===
def load_mnist_images(filename):
    with open(filename, 'rb') as f:
        _, num, rows, cols = struct.unpack(">IIII", f.read(16))
        images = np.frombuffer(f.read(), dtype=np.uint8).reshape(num, rows * cols)
        return images / 255.0

def load_mnist_labels(filename):
    with open(filename, 'rb') as f:
        _, num = struct.unpack(">II", f.read(8))
        labels = np.frombuffer(f.read(), dtype=np.uint8)
        return labels
 # Students can experiment to modify number of Train
X_train = load_mnist_images("train-images.idx3-ubyte__")[:500]
y_train = load_mnist_labels("train-labels.idx1-ubyte__")[:500]
X_test = load_mnist_images("t10k-images.idx3-ubyte__")[:200]
y_test = load_mnist_labels("t10k-labels.idx1-ubyte__")[:200]

# === Step 2: Activation Functions (Refer to Eq. 6.14 - 6.18) ===
def relu(x): return None
def tanh(x): return None
def softplus(x): return None
def leaky_relu(x, alpha=0.1): return None

def one_hot(y, num_classes=10): # Refer to Equation 6.36
    return None
def cross_entropy(y_pred, y_true): # Refer to Equation 6.36
    return None
def softmax(a): # Refer to Equation 6.37
    return None

def forward_pass(X, weights, activations): # Forward Pass (Eq. 6.19) ===
    return None

# === Step 3: Training Loop === # Students can experiment to modify
np.random.seed(42)
input_size = 784
hidden1 = 64
hidden2 = 16
output_size = 10
epochs = 1
best_loss = float('inf')
best_weights = None

for epoch in range(epochs):
    # TODO: Randomly initialize weights for each layer
    W1 = None
    W2 = None
    W3 = None

    weights = [W1, W2, W3]
    activations = [relu, relu, softmax]  # Students can experiment to modify

# === Step 4: Evaluation Metrics (Confusion Matrix, ROC, etc) ===
def compute_confusion_matrix(y_true, y_pred, num_classes=10): return None

# === ROC Curve ===
def compute_roc(y_true_oh, y_pred_proba):  return None

# === Classification Report === Print TP, FP, FN, TN, precision, recall, f1, accuracy
def compute_metrics(cm): return None

print("=== Classification Report === Print TP, FP, FN, TN, precision, recall, f1 for each class and overall accuracy")

